import os
import re
import smtplib
from email.message import EmailMessage
from typing import List, Optional
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from groq import Groq
from dotenv import load_dotenv

from portfolio_loader import build_dynamic_system_prompt, load_raw_portfolio_data

load_dotenv()

app = FastAPI(title="Aarav Shah Portfolio AI Assistant API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize Groq client
client = Groq(
    api_key=os.environ.get("GROQ_API_KEY"),
)

class ChatMessage(BaseModel):
    role: str  # "user", "assistant", "ai", or "system"
    content: str

class ChatRequest(BaseModel):
    message: Optional[str] = None
    messages: Optional[List[ChatMessage]] = None

class ContactRequest(BaseModel):
    name: str
    email: str
    message: str

PREFERRED_MODELS = [
    "openai/gpt-oss-120b",
    "qwen/qwen3.8-27b",
    "openai/gpt-oss-20b",
    "groq/compound",
    "llama-3.3-70b-versatile",
    "llama-3.1-8b-instant"
]

def clean_response(text: str) -> str:
    """Removes thinking/reasoning tags if generated by reasoning models."""
    if not text:
        return ""
    cleaned = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)
    return cleaned.strip()

@app.get("/")
def read_root():
    data = load_raw_portfolio_data()
    projects_count = len(data.get("projects", []))
    certs_count = len(data.get("certifications", []))
    return {
        "status": "ok",
        "assistant": "Aarav Shah Portfolio AI (Powered by Groq)",
        "synced_projects": projects_count,
        "synced_certifications": certs_count
    }

@app.post("/chat")
async def chat_endpoint(request: ChatRequest):
    try:
        # Dynamically load the latest system prompt synced with portfolioData.js
        system_prompt = build_dynamic_system_prompt()
        
        # Build message history
        conversation = [{"role": "system", "content": system_prompt}]
        
        if request.messages and len(request.messages) > 0:
            for msg in request.messages:
                role = "user" if msg.role == "user" else "assistant"
                conversation.append({"role": role, "content": msg.content})
        elif request.message:
            conversation.append({"role": "user", "content": request.message})
        else:
            raise HTTPException(status_code=400, detail="No message provided")

        # Try models in order of capability
        last_error = None
        for model_name in PREFERRED_MODELS:
            try:
                chat_completion = client.chat.completions.create(
                    messages=conversation,
                    model=model_name,
                    temperature=0.3,
                    max_tokens=1200,
                )
                raw_reply = chat_completion.choices[0].message.content
                reply = clean_response(raw_reply)
                if reply:
                    return {"reply": reply}
            except Exception as err:
                last_error = err
                continue

        # If all model attempts failed
        raise HTTPException(status_code=500, detail=f"Model inference failed: {str(last_error)}")
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/contact")
async def contact_endpoint(req: ContactRequest):
    name = req.name.strip()
    email = req.email.strip()
    message = req.message.strip()

    if not name or not email or not message:
        raise HTTPException(status_code=400, detail="Name, email, and message are all required.")

    smtp_email = os.environ.get("SMTP_EMAIL", "shahaarav2806@gmail.com")
    smtp_password = os.environ.get("SMTP_PASSWORD")
    recipient = os.environ.get("RECIPIENT_EMAIL", "shahaarav2806@gmail.com")

    if not smtp_password:
        return {
            "success": False,
            "message": "SMTP_PASSWORD not configured in backend .env. Set your Gmail 16-character App Password to enable backend email sending."
        }

    try:
        msg = EmailMessage()
        msg["Subject"] = f"Portfolio Inquiry from {name}"
        msg["From"] = smtp_email
        msg["To"] = recipient
        msg["Reply-To"] = email
        
        msg.set_content(
            f"You received a new portfolio inquiry:\n\n"
            f"Name: {name}\n"
            f"Email: {email}\n\n"
            f"Message:\n{message}\n"
        )

        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(smtp_email, smtp_password)
            server.send_message(msg)

        return {"success": True, "message": "Email sent successfully"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to send email: {str(e)}")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
